version: "3"
services:
  application:
    image: spring-boot-mysql-app
    ports:
      - "8484:8484"
    depends_on:
      - mysqldb
    volumes:
      - ./data/springboot-app:/data/springboot-app
  mysqldb:
    image: mysql:8.0
    ports:
     - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sbms
    volumes:
      - ./data/mysql:/data/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 3
      interval: 10s
      start_period: 30s
      timeout: 10s

volumes:
  springboot-app:
  mysql:

